name: "Chromatic"

on: push

jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm ci

      - name: Build Storybook
        run: npm run build-storybook

      - name: Publish to Chromatic
        uses: chromaui/action@latest
        with:
          # ⚠️ Certifique-se de configurar um `CHROMATIC_PROJECT_TOKEN` como um segredo do repositório
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}