name: Build and Publish Storybook to GitHub Pages

on:
  push:
    branches:
      - 'main' # Replace with the branch you want to deploy from

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - run: yarn install

      - run: yarn build-storybook

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          branch: gh-pages # The branch to deploy to
          folder: storybook-static # The folder containing the built Storybook
